"""added username,created_at and updated to User and created_at to post 

Revision ID: 06b171e5c797
Revises: b9dd26cfda61
Create Date: 2026-07-11 18:43:38.598004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b171e5c797'
down_revision: Union[str, Sequence[str], None] = 'b9dd26cfda61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'username')
    op.add_column('user_post', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'user_post', ['id'])
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'user_post', type_='unique')
    op.drop_column('user_post', 'created_at')
    op.add_column('user_auth', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
