"""added two columns to auth user

Revision ID: aacfb75b248c
Revises: 06b171e5c797
Create Date: 2026-07-12 21:12:34.052954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacfb75b248c'
down_revision: Union[str, Sequence[str], None] = '06b171e5c797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('security_code', sa.String(), nullable=True))
    op.add_column('user_auth', sa.Column('security_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('user_auth', 'security_code_expires_at')
    op.drop_column('user_auth', 'security_code')
    # ### end Alembic commands ###
